name: Publish
on:
  push:
    tags:
      - "v*"
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.3.2"
      - name: Install dependencies
        run: poetry install

      - name: Publish
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: |
          git fetch --unshallow --tags --force
          git checkout tags/$(git describe --tags --abbrev=0)
          poetry version $(git describe --tags --abbrev=0)
          poetry publish --build
