name: PyPi Publish
on:
  push:
    branches:
      - master
    tags:
      - "v*"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.3.2"

      - name: PyPi Publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          git fetch --unshallow --tags
          poetry version $(git describe --tags --abbrev=0)
          poetry build
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish
