name: PyPi Publish
on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: PyPi Publish
        uses: JRubics/poetry-publish@v1.16
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}